//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rider()
        {
            this.Team_Rider = new HashSet<Team_Rider>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Birth { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public bool Sex { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public string Introduction { get; set; }
        public Nullable<int> Classes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team_Rider> Team_Rider { get; set; }
    }
}
